# Generated by Django 3.2.7 on 2021-09-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('Linux', 'Linux'), ('MacOS', 'MacOS'), ('Windows', 'Windows')], default='Linux', max_length=50)),
                ('package_manager', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('linux', models.BooleanField(default=False)),
                ('mac_OS', models.BooleanField(default=False)),
                ('windows', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='softwares.installationmethod')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softwares.software')),
            ],
        ),
    ]
